server:
  port: ${SERVER_PORT:8888}
spring:
  application:
    name: spring-gateway
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
    serialization:
      indent_output: true
  cloud:
    gateway:
      routes:
        - id: rocketmq
          uri: lb://service-rocketmq
          predicates:
            - Path=/service-rocketmq/**
            - Method=GET
          filters:
            - StripPrefix=1
        - id: consumer
          uri: lb://service-consumer
          predicates:
            - Path=/service-consumer/**
            - Method=GET
          filters:
            - StripPrefix=1
        - id: provider
          uri: lb://service-provider
          predicates:
            - Path=/service-provider/**
            - Method=GET
          filters:
            - StripPrefix=1
            - Retry=5
      #        - id: http
      #          uri: http://demo.live.local:15088
      #          predicates:
      #            - Path=/http/**
      #            - Method=GET
      #          filters:
      #            - StripPrefix=1
      #          metadata:
      #            hostExpression: ${unit}-${host}
      discovery:
        locator:
          enabled: true
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
        namespace: ${NACOS_NAMESPACE:public}

logging:
  level:
    root: ${LIVE_LOG_LEVEL:INFO}