spring:
  application:
    name: grpc-consumer
  cloud:
    nacos:
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
      discovery:
        server-addr: ${NACOS_ADDR}
        namespace: ${NACOS_NAMESPACE:public}

grpc:
  client:
    grpc-provider:
      address: 'discovery:///grpc-provider'
      #static address
      #address: 'static://127.0.0.1:9898'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
      default-load-balancing-policy: round_robin

server:
  port: 8080 # Web Server