spring:
  application:
    name: sofarpc-consumer
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    default-property-inclusion: non_null
    serialization:
      indent_output: true
live:
  live-space-id: v4bEh4kd6Jvu5QBX09qYq-qlbcs
  rule-id: 1003
  uid: unit1
  lane-space-id:
  lane-code:

com:
  alipay:
    sofa:
      rpc:
        registry-address: nacos://${NACOS_ADDR}?username=${NACOS_USERNAME}&password=${NACOS_PASSWORD}&namespace=${NACOS_NAMESPACE}
logging:
  level:
    com.alipay.sofa.rpc: INFO