spring:
  application:
    name: sofarpc-provider
com:
  alipay:
    sofa:
      rpc:
        registry-address: nacos://${NACOS_ADDR}?username=${NACOS_USERNAME}&password=${NACOS_PASSWORD}&namespace=${NACOS_NAMESPACE}
        bind-network-interface: en0
logging:
  level:
    com.alipay.sofa.rpc: INFO