spring:
  application:
    name: grpc-provider
  cloud:
    nacos:
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
      discovery:
        server-addr: ${NACOS_ADDR}
        namespace: ${NACOS_NAMESPACE:public}
grpc:
  server:
    port: 9898
server:
  port: 8181
